### ISSUE TITLE
Does Elmap suit for high-dimension(larger than 3) dataset? 

### ISSUE THREAD

**Issue by lpw007** [Mirkes/ElMap#1]
I use the code to generate principal manifold in 9-dimensional data points, but the manifold is folding.

**Comment by Mirkes** [comment]
ElMap usually used for dimension greater than 3. You can see description of usage of ElMap for three high dimensional databases in folder doc of this repository. Shape of elastic map is defined by data distribution and parameters of map: stretch and bend.

**Comment by lpw007** [comment]
Thank you for your reply. I understand what you have said，but I don't know how to set parameters of map adaptively, It may be better to have different parameters for different nodes in the manifold than to have uniform parameters(stretch and bend).  And I think whether data points can be assigned to multiple nodes in the principal manifold? This approach looks more robust in the case of high noise

**Comment by Mirkes** [comment]
Presented implementation does not allow to specify different parameters for different nodes of map. Changing of stretch and banding is possible and described in examples and in commentaries in function EM.
Each data point associated with one map node only.
